version: '3'

services:
  server:
    image: webserver:latest
    restart: always
    ports:
      - 800:80
    networks:
      - webserver
    container_name: webserver
    volumes:
      - ./app_data:/srv
      - ./conf/container_nginx.conf:/etc/nginx/conf.d/default.conf
networks:
  webserver:
    driver: bridge
